name: Pylint Code Check (reusable)

on:
  workflow_call:
    inputs:
      path:
        description: "src folder"
        required: false
        type: string
        default: "src"
      python-version:
        required: false
        type: string
        default: "3.14"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Pylint
        run: |
          cd ${{ inputs.path }}
          pylint --exit-zero $(git ls-files '*.py')
